import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/Product.model.js";
import connectDB from "./config/db.js";

dotenv.config();

const products = [
  {
    name: "Apple iPhone 15 Pro",
    description: "Titanium design, A17 Pro chip.",
    price: 134900,
    category: "Mobiles",
    stock: 10,
    imageUrl: "https://m.media-amazon.com/images/I/81SigpJN1KL._SL1500_.jpg"
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    description: "AI features, 200MP camera.",
    price: 129999,
    category: "Mobiles",
    stock: 15,
    imageUrl: "https://m.media-amazon.com/images/I/81vxWpPpgNL._SL1500_.jpg"
  },
  {
    name: "Google Pixel 8 Pro",
    category: "Mobiles",
    price: 106999,
    stock: 20,
    description: "Advanced AI, best-in-class camera.",
    imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg"
  },
  { name: "OnePlus 12", category: "Mobiles", price: 64999, stock: 25, description: "Snapdragon 8 Gen 3, Hasselblad camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Xiaomi 14", category: "Mobiles", price: 69999, stock: 10, description: "Leica optics, compact flagship.", imageUrl: "https://m.media-amazon.com/images/I/71an9eiBxpL._SL1500_.jpg" },
  { name: "Nothing Phone (2)", category: "Mobiles", price: 39999, stock: 30, description: "Glyph interface, transparent design.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Samsung Galaxy Z Flip 5", category: "Mobiles", price: 99999, stock: 12, description: "Foldable pocket-sized design.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Realme GT 5 Pro", category: "Mobiles", price: 45000, stock: 18, description: "Flagship performance, budget price.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Vivo X100 Pro", category: "Mobiles", price: 89999, stock: 8, description: "Zeiss APO Floating Telephoto Camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Apple iPhone 13", category: "Mobiles", price: 52999, stock: 50, description: "A15 Bionic, dual-camera system.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Samsung Galaxy A54", category: "Mobiles", price: 34999, stock: 40, description: "Super AMOLED display, 50MP camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "OnePlus Nord 3", category: "Mobiles", price: 29999, stock: 35, description: "MediaTek Dimensity 9200+, fast charging.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Google Pixel 7a", category: "Mobiles", price: 44999, stock: 20, description: "AI-powered camera, smooth performance.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Motorola Edge 40", category: "Mobiles", price: 39999, stock: 15, description: "Edge-to-edge display, high refresh rate.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Sony Xperia 1 V", category: "Mobiles", price: 109999, stock: 10, description: "4K HDR OLED display, pro camera features.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Asus ROG Phone 7", category: "Mobiles", price: 79999, stock: 12, description: "Gaming phone with AirTrigger controls.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Oppo Find X6 Pro", category: "Mobiles", price: 94999, stock: 18, description: "Ultra-premium design, advanced camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Realme Narzo 60x", category: "Mobiles", price: 14999, stock: 25, description: "Budget-friendly with decent performance.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Infinix Zero Ultra", category: "Mobiles", price: 29999, stock: 30, description: "Affordable flagship with 200MP camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Tecno Phantom X2", category: "Mobiles", price: 24999, stock: 20, description: "Stylish design with AI camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Lava Agni 2", category: "Mobiles", price: 19999, stock: 15, description: "Made in India, gaming-focused.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Micromax IN 2b", category: "Mobiles", price: 9999, stock: 50, description: "Affordable smartphone with decent specs.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Infinix Note 30", category: "Mobiles", price: 12999, stock: 40, description: "Large display, long battery life.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Realme GT Neo5", category: "Mobiles", price: 24999, stock: 25, description: "Snapdragon 8 Gen 2, fast charging.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Samsung Galaxy M14", category: "Mobiles", price: 11999, stock: 30, description: "Budget-friendly with large battery.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Apple iPhone SE (2024)", category: "Mobiles", price: 44999, stock: 20, description: "Compact design with A15 Bionic chip.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Google Pixel 8a", category: "Mobiles", price: 39999, stock: 15, description: "Affordable Pixel with AI features.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "OnePlus 12T", category: "Mobiles", price: 54999, stock: 10, description: "Flagship performance with Hasselblad camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Xiaomi Redmi Note 13 Pro", category: "Mobiles", price: 17999, stock: 25, description: "Budget-friendly with AMOLED display.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Vivo V30 Pro", category: "Mobiles", price: 29999, stock: 20, description: "Stylish design with advanced camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Oppo Reno 12", category: "Mobiles", price: 24999, stock: 15, description: "Sleek design with fast charging.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Asus Zenfone 10", category: "Mobiles", price: 39999, stock: 10, description: "Compact flagship with Snapdragon 8 Gen 2.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Motorola Edge 40 Pro", category: "Mobiles", price: 49999, stock: 12, description: "Premium design with high refresh rate.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Sony Xperia 5 V", category: "Mobiles", price: 79999, stock: 8, description: "Compact flagship with 4K HDR OLED display.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Realme GT 5 Pro", category: "Mobiles", price: 64999, stock: 18, description: "Flagship performance with Hasselblad camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Infinix Zero Ultra", category: "Mobiles", price: 29999, stock: 20, description: "Affordable flagship with 200MP camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  {name: "Tecno Phantom X2", category: "Mobiles", price: 24999, stock: 15, description: "Stylish design with AI camera.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },

  // Laptops
  { name: "MacBook Air M2", category: "Laptops", price: 99900, stock: 20, description: "Supercharged by M2, 13.6-inch Liquid Retina.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Dell XPS 13", category: "Laptops", price: 145000, stock: 10, description: "InfinityEdge display, premium build.", imageUrl: "https://m.media-amazon.com/images/I/71an9eiBxpL._SL1500_.jpg" },
  { name: "HP Spectre x360", category: "Laptops", price: 135000, stock: 15, description: "2-in-1 convertible, OLED display.", imageUrl: "https://m.media-amazon.com/images/I/71Kwi8zU+DL._SL1500_.jpg" },
  { name: "Lenovo ThinkPad X1 Carbon", category: "Laptops", price: 160000, stock: 12, description: "Business flagship, durable and light.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Asus ROG Zephyrus G14", category: "Laptops", price: 120000, stock: 25, description: "Gaming powerhouse, AniMe Matrix.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Acer Swift Go 14", category: "Laptops", price: 65000, stock: 30, description: "OLED display, Intel Core Ultra.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Microsoft Surface Laptop 5", category: "Laptops", price: 110000, stock: 18, description: "Sleek design, touchscreen.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "MSI Raider GE78", category: "Laptops", price: 250000, stock: 5, description: "High-end gaming, RGB lighting.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "LG Gram 17", category: "Laptops", price: 140000, stock: 10, description: "Ultra-lightweight, long battery life.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Razer Blade 15", category: "Laptops", price: 220000, stock: 7, description: "Premium gaming laptop, CNC aluminum.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Samsung Galaxy Book3 Pro", category: "Laptops", price: 130000, stock: 12, description: "Sleek design, AMOLED display.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Huawei MateBook X Pro", category: "Laptops", price: 150000, stock: 8, description: "High-resolution touchscreen, slim design.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Alienware x17 R2", category: "Laptops", price: 280000, stock: 5, description: "Gaming beast, advanced cooling.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Toshiba Dynabook X30", category: "Laptops", price: 90000, stock: 15, description: "Business laptop, lightweight and durable.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Gigabyte Aero 16", category: "Laptops", price: 200000, stock: 10, description: "Creator-focused laptop, OLED display.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Razer Blade 17", category: "Laptops", price: 300000, stock: 5, description: "High-end gaming laptop, premium build.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Apple MacBook Pro 16-inch", category: "Laptops", price: 250000, stock: 8, description: "M1 Pro chip, Liquid Retina XDR display.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Dell Alienware m15 R7", category: "Laptops", price: 240000, stock: 6, description: "Gaming laptop with advanced cooling.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "HP Omen 16", category: "Laptops", price: 180000, stock: 10, description: "Gaming laptop with high refresh rate.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Lenovo Legion 7i", category: "Laptops", price: 220000, stock: 7, description: "Gaming laptop with Intel Core i9.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Asus ZenBook Pro Duo 15", category: "Laptops", price: 210000, stock: 5, description: "Dual-screen laptop for creators.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "Acer Predator Helios 300", category: "Laptops", price: 190000, stock: 12, description: "Gaming laptop with NVIDIA RTX graphics.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },
  { name: "MSI Stealth 15M", category: "Laptops", price: 200000, stock: 8, description: "Slim gaming laptop with high performance.", imageUrl: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._SL1500_.jpg" },

  // Toys
  { name: "LEGO Star Wars Millennium Falcon", category: "Toys", price: 15999, stock: 10, description: "Detailed LEGO model.", imageUrl: "https://m.media-amazon.com/images/I/615afIGJirL._SX679_.jpg" },
  { name: "Barbie Dreamhouse", category: "Toys", price: 12999, stock: 15, description: "3-story dollhouse with slide.", imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcS18o7lJ60IQWdyGFpAoIoVcajvH8I-tixCNTQ2VtM59LnSZhJTOaKL0nQ9GVCkORCKlECSn5XVlS3KzBXmDZVtTWj4JjzcGcbnJ8BpCBJp_E0nSiImleFjpg" },
  { name: "Hot Wheels 10-Car Pack", category: "Toys", price: 1499, stock: 50, description: "Set of 10 die-cast cars.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Nerf Elite 2.0 Commander", category: "Toys", price: 999, stock: 40, description: "Blaster with 12 darts.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Rubik's Cube 3x3", category: "Toys", price: 399, stock: 100, description: "The original color-matching puzzle.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Play-Doh Modeling Compound", category: "Toys", price: 299, stock: 80, description: "Pack of 4 colors.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Remote Control Car", category: "Toys", price: 1999, stock: 25, description: "High speed off-road RC car.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Uno Card Game", category: "Toys", price: 199, stock: 150, description: "Classic card game.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Fisher-Price Laugh & Learn", category: "Toys", price: 2499, stock: 30, description: "Interactive learning toy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "LEGO Friends Heartlake City", category: "Toys", price: 7999, stock: 20, description: "LEGO set with mini-dolls.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Transformers Action Figure", category: "Toys", price: 1499, stock: 35, description: "Transforming robot toy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Hot Wheels Track Set", category: "Toys", price: 2999, stock: 15, description: "Race track with loops and jumps.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Playmobil Pirate Ship", category: "Toys", price: 4999, stock: 10, description: "Pirate ship playset with figures.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Barbie Fashionista Doll", category: "Toys", price: 999, stock: 50, description: "Fashion doll with accessories.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "LEGO Technic Bugatti Chiron", category: "Toys", price: 15999, stock: 5, description: "Detailed LEGO Technic model.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Fisher-Price Little People Farm", category: "Toys", price: 1999, stock: 20, description: "Farm playset with animals.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Nerf Ultra One Blaster", category: "Toys", price: 2499, stock: 30, description: "High-capacity blaster with darts.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "LEGO Creator Expert Roller Coaster", category: "Toys", price: 19999, stock: 8, description: "Advanced LEGO set with working coaster.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Hot Wheels Monster Trucks", category: "Toys", price: 999, stock: 40, description: "Set of 4 monster trucks.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Foods
  { name: "Ferrero Rocher (24 Pieces)", category: "Foods", price: 999, stock: 50, description: "Premium hazelnut chocolates.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Green Tea", category: "Foods", price: 499, stock: 60, description: "100 tea bags, detox.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Peanut Butter (1kg)", category: "Foods", price: 599, stock: 40, description: "Crunchy, high protein.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "California Almonds (500g)", category: "Foods", price: 650, stock: 45, description: "Premium quality almonds.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Extra Virgin Olive Oil (1L)", category: "Foods", price: 1200, stock: 30, description: "Cold pressed, healthy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Instant Coffee (200g)", category: "Foods", price: 750, stock: 55, description: "Rich aroma, 100% pure coffee.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Basmati Rice (5kg)", category: "Foods", price: 899, stock: 35, description: "Long grain, aromatic.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dark Chocolate Bar", category: "Foods", price: 250, stock: 80, description: "85% Cocoa, intense flavor.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Honey (500g)", category: "Foods", price: 399, stock: 60, description: "Pure natural honey.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Protein Bar Box", category: "Foods", price: 1500, stock: 25, description: "Pack of 6, chocolate flavor.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Quinoa (1kg)", category: "Foods", price: 799, stock: 40, description: "High protein, gluten-free.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cashew Nuts (500g)", category: "Foods", price: 699, stock: 50, description: "Premium quality cashews.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Chia Seeds (500g)", category: "Foods", price: 499, stock: 70, description: "Rich in omega-3 and fiber.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Almond Butter (250g)", category: "Foods", price: 899, stock: 30, description: "Smooth and creamy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Oats (1kg)", category: "Foods", price: 399, stock: 80, description: "Whole grain, high fiber.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Trail Mix (500g)", category: "Foods", price: 599, stock: 45, description: "Nuts and dried fruits mix.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Coconut Water (1L)", category: "Foods", price: 199, stock: 100, description: "Refreshing and natural.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Turmeric Powder (250g)", category: "Foods", price: 299, stock: 60, description: "Anti-inflammatory and antioxidant.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Greek Yogurt (500g)", category: "Foods", price: 249, stock: 70, description: "High protein, creamy texture.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Almond Milk (1L)", category: "Foods", price: 399, stock: 50, description: "Dairy-free, enriched with vitamins.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dark Chocolate Almonds (200g)", category: "Foods", price: 499, stock: 40, description: "Almonds coated in dark chocolate.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Matcha Powder (100g)", category: "Foods", price: 799, stock: 30, description: "Premium ceremonial grade matcha.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Protein Powder (1kg)", category: "Foods", price: 1999, stock: 20, description: "Whey protein for muscle recovery.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Flax Seeds (500g)", category: "Foods", price: 399, stock: 60, description: "Rich in omega-3 and fiber.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cacao Nibs (250g)", category: "Foods", price: 599, stock: 40, description: "Raw cacao for baking and smoothies.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Organic Honeycomb (200g)", category: "Foods", price: 699, stock: 30, description: "Natural honeycomb for direct consumption.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Cosmetics
  { name: "Maybelline Mascara", category: "Cosmetics", price: 450, stock: 60, description: "Volume express, waterproof.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "MAC Matte Lipstick", category: "Cosmetics", price: 1950, stock: 40, description: "Long lasting, velvet finish.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Lakme Eye Liner", category: "Cosmetics", price: 350, stock: 80, description: "Intense black, smudge proof.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Nivea Soft Moisturizer", category: "Cosmetics", price: 299, stock: 100, description: "Light moisturizer for face and body.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "L'Oreal Paris Shampoo", category: "Cosmetics", price: 699, stock: 50, description: "Total repair, 1 litre.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Neutrogena Sunscreen", category: "Cosmetics", price: 550, stock: 70, description: "SPF 50+, ultra sheer.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Body Shop Shower Gel", category: "Cosmetics", price: 495, stock: 45, description: "British Rose, 250ml.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Face Serum Vitamin C", category: "Cosmetics", price: 899, stock: 35, description: "Brightening and anti-aging.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Nail Polish Set", category: "Cosmetics", price: 499, stock: 60, description: "Pack of 5 pastel colors.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Makeup Brush Set", category: "Cosmetics", price: 999, stock: 30, description: "12 piece professional set.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Revlon Hair Dryer", category: "Cosmetics", price: 1499, stock: 25, description: "2000W, multiple heat settings.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  { name: "Garnier Face Wash", category: "Cosmetics", price: 299, stock: 80, description: "For all skin types, 100ml.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dove Body Lotion", category: "Cosmetics", price: 399, stock: 70, description: "Deeply nourishes and hydrates.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Clinique Moisturizer", category: "Cosmetics", price: 1299, stock: 40, description: "Hydrating gel-cream for dry skin.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Estée Lauder Foundation", category: "Cosmetics", price: 2999, stock: 30, description: "Long-wear, flawless finish.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Urban Decay Eyeshadow Palette", category: "Cosmetics", price: 2499, stock: 20, description: "12 shades, highly pigmented.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Benefit Brow Kit", category: "Cosmetics", price: 1499, stock: 25, description: "Complete brow shaping kit.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Tarte Blush", category: "Cosmetics", price: 1999, stock: 15, description: "Amazonian clay blush for a natural flush.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Too Faced Lip Gloss", category: "Cosmetics", price: 1299, stock: 20, description: "High-shine, non-sticky formula.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "NYX Professional Makeup Setting Spray", category: "Cosmetics", price: 799, stock: 30, description: "Keeps makeup in place all day.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sephora Collection Lipstick", category: "Cosmetics", price: 999, stock: 25, description: "Rich color and smooth application.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "L'Oreal Paris Hair Serum", category: "Cosmetics", price: 699, stock: 40, description: "Smooths frizz and adds shine.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kiehl's Facial Cream", category: "Cosmetics", price: 2499, stock: 20, description: "Hydrating cream for all skin types.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Shiseido Eye Cream", category: "Cosmetics", price: 3999, stock: 15, description: "Reduces puffiness and dark circles.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Clinique Lip Balm", category: "Cosmetics", price: 599, stock: 50, description: "Moisturizing and soothing lip balm.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bobbi Brown Foundation Stick", category: "Cosmetics", price: 2999, stock: 20, description: "Creamy foundation for a natural finish.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Lancôme Mascara", category: "Cosmetics", price: 2499, stock: 30, description: "Volumizing mascara for long lashes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dior Lipstick", category: "Cosmetics", price: 3499, stock: 15, description: "Luxurious lipstick with rich color.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Books
  { name: "The Alchemist", category: "Books", price: 299, stock: 100, description: "A novel by Paulo Coelho.", imageUrl: "https://m.media-amazon.com/images/I/51Z0nLAfLmL._SX320_BO1,204,203,200_.jpg" },
  { name: "Atomic Habits", category: "Books", price: 450, stock: 80, description: "Build good habits, break bad ones.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Psychology of Money", category: "Books", price: 399, stock: 90, description: "Timeless lessons on wealth.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Harry Potter & Sorcerer's Stone", category: "Books", price: 599, stock: 60, description: "Book 1 of Harry Potter series.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Ikigai", category: "Books", price: 350, stock: 75, description: "Japanese secret to a long life.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Great Gatsby", category: "Books", price: 250, stock: 40, description: "Classic novel by F. Scott Fitzgerald.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "To Kill a Mockingbird", category: "Books", price: 299, stock: 45, description: "Harper Lee's masterpiece.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "1984", category: "Books", price: 250, stock: 55, description: "Dystopian novel by George Orwell.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sapiens: A Brief History of Humankind", category: "Books", price: 499, stock: 70, description: "Explores the history of humankind.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Subtle Art of Not Giving a F*ck", category: "Books", price: 399, stock: 65, description: "A counterintuitive approach to living a good life.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Thinking, Fast and Slow", category: "Books", price: 450, stock: 50, description: "Explores the two systems of thought.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Power of Habit", category: "Books", price: 399, stock: 60, description: "Why we do what we do in life and business.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Lean Startup", category: "Books", price: 499, stock: 55, description: "How today's entrepreneurs use continuous innovation.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The 7 Habits of Highly Effective People", category: "Books", price: 599, stock: 45, description: "Powerful lessons in personal change.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Rich Dad Poor Dad", category: "Books", price: 399, stock: 70, description: "What the rich teach their kids about money.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Art of War", category: "Books", price: 299, stock: 80, description: "Ancient Chinese military treatise.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Catcher in the Rye", category: "Books", price: 350, stock: 60, description: "Novel by J.D. Salinger.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Hobbit", category: "Books", price: 399, stock: 50, description: "Fantasy novel by J.R.R. Tolkien.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Road Less Traveled", category: "Books", price: 450, stock: 40, description: "A new psychology of love, traditional values and spiritual growth.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWy  L._SL1500_.jpg" },
  { name: "The Four Agreements", category: "Books", price: 299, stock: 70, description: "A practical guide to personal freedom.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Five Love Languages", category: "Books", price: 399, stock: 60, description: "How to express heartfelt commitment to your mate.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Power of Now", category: "Books", price: 499, stock: 50, description: "A guide to spiritual enlightenment.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The 48 Laws of Power", category: "Books", price: 599, stock: 40, description: "A guide to power dynamics and strategy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Art of Happiness", category: "Books", price: 399, stock: 70, description: "A handbook for living.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Secret", category: "Books", price: 299, stock: 80, description: "The law of attraction and positive thinking.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Magic of Thinking Big", category: "Books", price: 350, stock: 60, description: "Achieve success and happiness.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The One Thing", category: "Books", price: 399, stock: 50, description: "The surprisingly simple truth behind extraordinary results.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Miracle Morning", category: "Books", price: 450, stock: 40, description: "The not-so-obvious secret guaranteed to transform your life.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Compound Effect", category: "Books", price: 299, stock: 70, description: "Jumpstart your income, your life, your success.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Slight Edge", category: "Books", price: 399, stock: 60, description: "Turning simple disciplines into massive success and happiness.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The War of Art", category: "Books", price: 499, stock: 50, description: "Break through the blocks and win your inner creative battles.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Untethered Soul", category: "Books", price: 599, stock: 40, description: "The journey beyond yourself.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Book Thief", category: "Books", price: 399, stock: 70, description: "A novel by Markus Zusak.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Night Circus", category: "Books", price: 299, stock: 80, description: "A novel by Erin Morgenstern.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Goldfinch", category: "Books", price: 350, stock: 60, description: "A novel by Donna Tartt.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Road", category: "Books", price: 399, stock: 50, description: "A novel by Cormac McCarthy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "The Handmaid's Tale", category: "Books", price: 450, stock: 40, description: "A novel by Margaret Atwood.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Stationery
  { name: "Parker Vector Pen", category: "Stationery", price: 350, stock: 100, description: "Standard rollerball pen.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Faber-Castell Pencils", category: "Stationery", price: 150, stock: 200, description: "Pack of 10 wooden pencils.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pilot V5 Pen Set", category: "Stationery", price: 250, stock: 150, description: "Pack of 3 liquid ink pens.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Staedtler Mars Lumograph", category: "Stationery", price: 800, stock: 50, description: "Art drawing pencils set.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Moleskine Classic Notebook", category: "Stationery", price: 1500, stock: 30, description: "Hard cover, ruled pages.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sticky Notes Pad", category: "Stationery", price: 99, stock: 300, description: "Neon colors, 400 sheets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Highlighters Set", category: "Stationery", price: 199, stock: 120, description: "Pack of 5 fluorescent colors.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Geometry Box", category: "Stationery", price: 250, stock: 80, description: "Complete mathematical set.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Whiteboard Markers", category: "Stationery", price: 300, stock: 90, description: "Pack of 4, erasable.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Fountain Pen Ink", category: "Stationery", price: 200, stock: 60, description: "Royal Blue, 60ml bottle.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sketching Pencils Set", category: "Stationery", price: 350, stock: 70, description: "Set of 12 graphite pencils.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Eraser Pack", category: "Stationery", price: 50, stock: 200, description: "Pack of 5 soft erasers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sharpener Set", category: "Stationery", price: 100, stock: 150, description: "Pack of 3 pencil sharpeners.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Drawing Paper Pad", category: "Stationery", price: 400, stock: 40, description: "A4 size, 100 sheets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Calligraphy Pen Set", category: "Stationery", price: 600, stock: 30, description: "Includes 3 nibs and ink.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sticky Tabs", category: "Stationery", price: 150, stock: 100, description: "Pack of 6 colors, 300 tabs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Binder Clips Set", category: "Stationery", price: 120, stock: 80, description: "Pack of 12 assorted sizes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Stapler Set", category: "Stationery", price: 250, stock: 60, description: "Includes stapler and staples.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Index Cards", category: "Stationery", price: 200, stock: 90, description: "Pack of 100 ruled cards.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Desk Organizer", category: "Stationery", price: 499, stock: 40, description: "Multi-compartment organizer.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Whiteboard Eraser", category: "Stationery", price: 150, stock: 70, description: "Magnetic eraser for whiteboards.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sticky Note Dispenser", category: "Stationery", price: 299, stock: 50, description: "Holds sticky notes for easy access.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Desk Calendar", category: "Stationery", price: 399, stock: 30, description: "2024 desk calendar with notes section.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },


  // Footwear
  { name: "Nike Air Max", category: "Footwear", price: 8999, stock: 20, description: "Comfortable running shoes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Adidas Ultraboost", category: "Footwear", price: 11999, stock: 15, description: "High performance running shoes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Puma Sneakers", category: "Footwear", price: 4500, stock: 30, description: "Casual white sneakers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Converse Chuck Taylor", category: "Footwear", price: 3999, stock: 40, description: "Classic high-top canvas shoes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Vans Old Skool", category: "Footwear", price: 4999, stock: 25, description: "Skate shoes, suede canvas.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Woodland Boots", category: "Footwear", price: 5500, stock: 20, description: "Rugged leather boots.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Crocs Classic Clogs", category: "Footwear", price: 2995, stock: 50, description: "Comfortable and lightweight.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Reebok Training Shoes", category: "Footwear", price: 3500, stock: 35, description: "Gym and workout shoes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Formal Oxford Shoes", category: "Footwear", price: 2500, stock: 40, description: "Black leather formal shoes.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's High Heels", category: "Footwear", price: 2999, stock: 30, description: "Stiletto pumps, beige.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Men's Fashion
  { name: "Levi's Men's Jeans", category: "Men's Fashion", price: 2999, stock: 50, description: "511 Slim Fit.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "US Polo T-Shirt", category: "Men's Fashion", price: 1299, stock: 60, description: "Cotton polo neck.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Raymond Formal Shirt", category: "Men's Fashion", price: 1599, stock: 40, description: "White cotton formal shirt.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Denim Jacket", category: "Men's Fashion", price: 2499, stock: 30, description: "Classic blue denim jacket.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Chinos", category: "Men's Fashion", price: 1899, stock: 45, description: "Beige slim fit trousers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Puma Hoodie", category: "Men's Fashion", price: 2299, stock: 35, description: "Black fleece hoodie.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Blazer", category: "Men's Fashion", price: 4999, stock: 20, description: "Navy blue casual blazer.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cargo Pants", category: "Men's Fashion", price: 1999, stock: 40, description: "Olive green, multi pockets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cotton Kurta", category: "Men's Fashion", price: 999, stock: 50, description: "Traditional wear, white.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Leather Belt", category: "Men's Fashion", price: 799, stock: 70, description: "Brown genuine leather belt.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Sports Watch", category: "Men's Fashion", price: 2999, stock: 25, description: "Water-resistant digital watch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Leather Wallet", category: "Men's Fashion", price: 1499, stock: 30, description: "Bifold wallet with card slots.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Casual Shirt", category: "Men's Fashion", price: 1299, stock: 40, description: "Checkered cotton shirt.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" }, 
  { name: "Men's Formal Trousers", category: "Men's Fashion", price: 1999, stock: 35, description: "Black slim fit formal trousers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Casual Sneakers", category: "Men's Fashion", price: 3499, stock: 30, description: "White low-top sneakers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Winter Jacket", category: "Men's Fashion", price: 5999, stock: 20, description: "Padded jacket for cold weather.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Men's Shorts", category: "Men's Fashion", price: 799, stock: 70, description: "Casual cotton shorts.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Women's Fashion
  { name: "Floral Summer Dress", category: "Women's Fashion", price: 1499, stock: 50, description: "Cotton midi dress.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Silk Saree", category: "Women's Fashion", price: 3999, stock: 30, description: "Traditional Banarasi silk.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cotton Kurti", category: "Women's Fashion", price: 899, stock: 60, description: "Printed daily wear kurti.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's Leggings", category: "Women's Fashion", price: 499, stock: 100, description: "Stretchable cotton leggings.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pleated Skirt", category: "Women's Fashion", price: 1299, stock: 40, description: "Midi length, black.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Designer Blouse", category: "Women's Fashion", price: 1599, stock: 25, description: "Readymade saree blouse.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Winter Cardigan", category: "Women's Fashion", price: 1999, stock: 35, description: "Woolen knitwear.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Stylish Jumpsuit", category: "Women's Fashion", price: 1799, stock: 30, description: "Casual wear jumpsuit.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Silk Scarf", category: "Women's Fashion", price: 699, stock: 50, description: "Printed square scarf.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Denim Jacket", category: "Women's Fashion", price: 2499, stock: 20, description: "Blue denim casual jacket.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Evening Gown", category: "Women's Fashion", price: 4999, stock: 15, description: "Elegant evening wear.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Summer Sandals", category: "Women's Fashion", price: 1299, stock: 40, description: "Comfortable open-toe sandals.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's Blazer", category: "Women's Fashion", price: 2999, stock: 25, description: "Formal office wear blazer.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Maxi Dress", category: "Women's Fashion", price: 1999, stock: 30, description: "Flowy summer maxi dress.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Crop Top", category: "Women's Fashion", price: 799, stock: 70, description: "Casual cotton crop top.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's Ankle Boots", category: "Women's Fashion", price: 3499, stock: 20, description: "Leather ankle boots.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Palazzo Pants", category: "Women's Fashion", price: 999, stock: 55, description: "Wide leg comfortable pants.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Kids' Fashion
  { name: "Kids Graphic T-Shirt", category: "Kids' Fashion", price: 499, stock: 80, description: "Cotton, superhero print.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Baby Onesie Pack", category: "Kids' Fashion", price: 999, stock: 60, description: "Pack of 3, soft cotton.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kids Denim Jeans", category: "Kids' Fashion", price: 1199, stock: 50, description: "Elastic waist, durable.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Party Wear Frock", category: "Kids' Fashion", price: 1499, stock: 40, description: "Pink satin dress.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "School Uniform Shirt", category: "Kids' Fashion", price: 599, stock: 100, description: "White cotton shirt.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kids Fleece Hoodie", category: "Kids' Fashion", price: 1299, stock: 45, description: "Warm winter wear.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cotton Pajama Set", category: "Kids' Fashion", price: 899, stock: 55, description: "Nightwear for kids.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kids Shorts", category: "Kids' Fashion", price: 599, stock: 70, description: "Summer wear.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Winter Puffer Jacket", category: "Kids' Fashion", price: 1999, stock: 30, description: "Insulated jacket.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kids Cap", category: "Kids' Fashion", price: 399, stock: 60, description: "Baseball cap.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Bags
  { name: "Laptop Backpack", category: "Bags", price: 1999, stock: 50, description: "Water resistant, fits 15 inch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Travel Suitcase", category: "Bags", price: 4999, stock: 20, description: "Hard shell, 4 wheels.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's Handbag", category: "Bags", price: 2499, stock: 40, description: "Leather tote bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Canvas Tote Bag", category: "Bags", price: 599, stock: 80, description: "Eco friendly shopping bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sling Bag", category: "Bags", price: 999, stock: 60, description: "Compact crossbody bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Gym Duffle Bag", category: "Bags", price: 1299, stock: 45, description: "Shoe compartment included.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Leather Wallet", category: "Bags", price: 899, stock: 70, description: "Bi-fold men's wallet.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Party Clutch", category: "Bags", price: 1499, stock: 35, description: "Golden embellished clutch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Hiking Rucksack", category: "Bags", price: 3999, stock: 15, description: "60L capacity, rain cover.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Messenger Bag", category: "Bags", price: 1799, stock: 30, description: "Office bag for documents.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Laptop Sleeve", category: "Bags", price: 799, stock: 50, description: "Protective sleeve for laptops.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Travel Backpack", category: "Bags", price: 2999, stock: 25, description: "Multi-compartment travel backpack.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Crossbody Bag", category: "Bags", price: 1299, stock: 40, description: "Adjustable strap, casual wear.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Tote Bag", category: "Bags", price: 999, stock: 60, description: "Spacious tote for daily use.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Rolling Luggage", category: "Bags", price: 5999, stock: 10, description: "Spinner wheels, TSA lock.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Laptop Backpack", category: "Bags", price: 1999, stock: 50, description: "Water resistant, fits 15 inch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Travel Suitcase", category: "Bags", price: 4999, stock: 20, description: "Hard shell, 4 wheels.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's Handbag", category: "Bags", price: 2499, stock: 40, description: "Leather tote bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Canvas Tote Bag", category: "Bags", price: 599, stock: 80, description: "Eco friendly shopping bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sling Bag", category: "Bags", price: 999, stock: 60, description: "Compact crossbody bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Gym Duffle Bag", category: "Bags", price: 1299, stock: 45, description: "Shoe compartment included.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Leather Wallet", category: "Bags", price: 899, stock: 70, description: "Bi-fold men's wallet.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Party Clutch", category: "Bags", price: 1499, stock: 35, description: "Golden embellished clutch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Hiking Rucksack", category: "Bags", price: 3999, stock: 15, description: "60L capacity, rain cover.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Messenger Bag", category: "Bags", price: 1799, stock: 30, description: "Office bag for documents.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Laptop Sleeve", category: "Bags", price: 799, stock: 50, description: "Protective sleeve for laptops.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Travel Backpack", category: "Bags", price: 2999, stock: 25, description: "Multi-compartment travel backpack.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Crossbody Bag", category: "Bags", price: 1299, stock: 40, description: "Adjustable strap, casual wear.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Tote Bag", category: "Bags", price: 999, stock: 60, description: "Spacious tote for daily use.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Rolling Luggage", category: "Bags", price: 5999, stock: 10, description: "Spinner wheels, TSA lock.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Laptop Backpack", category: "Bags", price: 1999, stock: 50, description: "Water resistant, fits 15 inch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Travel Suitcase", category: "Bags", price: 4999, stock: 20, description: "Hard shell, 4 wheels.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Women's Handbag", category: "Bags", price: 2499, stock: 40, description: "Leather tote bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Canvas Tote Bag", category: "Bags", price: 599, stock: 80, description: "Eco friendly shopping bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sling Bag", category: "Bags", price: 999, stock: 60, description: "Compact crossbody bag.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Gym Duffle Bag", category: "Bags", price: 1299, stock: 45, description: "Shoe compartment included.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Messenger Bag", category: "Bags", price: 1799, stock: 30, description: "Office bag for documents.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Bottles (Home)
  { name: "Steel Water Bottle", category: "Home", price: 599, stock: 100, description: "1 Litre, insulated.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Glass Water Bottle", category: "Home", price: 499, stock: 60, description: "With silicone sleeve.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Thermos Flask", category: "Home", price: 1299, stock: 40, description: "Keeps hot for 12 hours.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Sports Sipper", category: "Home", price: 399, stock: 80, description: "BPA free plastic.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Copper Bottle", category: "Home", price: 999, stock: 50, description: "Health benefits, 1L.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Fruit Infuser Bottle", category: "Home", price: 699, stock: 45, description: "Detox water bottle.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kids Water Bottle", category: "Home", price: 450, stock: 70, description: "Cartoon print, straw.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Tupperware Set", category: "Home", price: 1499, stock: 30, description: "Set of 4 bottles.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Protein Shaker", category: "Home", price: 299, stock: 90, description: "With mixing ball.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Travel Mug", category: "Home", price: 899, stock: 55, description: "Leak proof coffee mug.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Sports
  { name: "Cricket Bat", category: "Sports", price: 1299, stock: 50, description: "English Willow bat.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Football Size 5", category: "Sports", price: 899, stock: 40, description: "Standard match ball.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Badminton Racket", category: "Sports", price: 1500, stock: 30, description: "Lightweight graphite.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Yoga Mat", category: "Sports", price: 699, stock: 60, description: "Anti-slip 6mm mat.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dumbbells (5kg Pair)", category: "Sports", price: 1999, stock: 25, description: "Rubber coated hex dumbbells.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Tennis Ball Set", category: "Sports", price: 399, stock: 100, description: "Pack of 3 balls.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Skipping Rope", category: "Sports", price: 199, stock: 80, description: "Adjustable speed rope.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Swimming Goggles", category: "Sports", price: 499, stock: 45, description: "Anti-fog UV protection.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Table Tennis Set", category: "Sports", price: 899, stock: 30, description: "Includes paddles and balls.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Golf Club Set", category: "Sports", price: 9999, stock: 10, description: "Complete set for beginners.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Boxing Gloves", category: "Sports", price: 2499, stock: 20, description: "Leather gloves for training.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Resistance Bands Set", category: "Sports", price: 799, stock: 50, description: "Set of 5 resistance bands.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Treadmill", category: "Sports", price: 29999, stock: 5, description: "Motorized treadmill for home use.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Exercise Bike", category: "Sports", price: 15999, stock: 8, description: "Stationary bike for cardio workouts.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pull-Up Bar", category: "Sports", price: 1299, stock: 15, description: "Doorway mounted pull-up bar.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Kettlebell Set", category: "Sports", price: 4999, stock: 12, description: "Set of 3 kettlebells.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Jump Rope", category: "Sports", price: 299, stock: 70, description: "Adjustable length jump rope.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Foam Roller", category: "Sports", price: 699, stock: 25, description: "For muscle recovery and massage.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Resistance Loop Bands", category: "Sports", price: 499, stock: 60, description: "Set of 5 loop bands.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Yoga Block", category: "Sports", price: 399, stock: 40, description: "Foam block for yoga poses.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pilates Ring", category: "Sports", price: 799, stock: 30, description: "Resistance ring for Pilates exercises.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Agility Ladder", category: "Sports", price: 999, stock: 20, description: "For speed and agility training.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Speed Jump Rope", category: "Sports", price: 599, stock: 50, description: "For cardio and endurance training.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Medicine Ball", category: "Sports", price: 1499, stock: 25, description: "Weighted ball for strength training.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pull-Up Assist Bands", category: "Sports", price: 699, stock: 30, description: "Set of 3 bands for pull-up assistance.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cycling Helmet", category: "Sports", price: 1299, stock: 20, description: "Safety certified helmet.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Basketball", category: "Sports", price: 999, stock: 35, description: "Outdoor rubber basketball.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Furniture
  { name: "Office Chair", category: "Furniture", price: 4999, stock: 20, description: "Ergonomic mesh chair.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Study Table", category: "Furniture", price: 3500, stock: 15, description: "Wooden desk with drawers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bean Bag (XXL)", category: "Furniture", price: 1299, stock: 30, description: "With beans, faux leather.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bookshelf", category: "Furniture", price: 2999, stock: 10, description: "4-tier wooden shelf.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Shoe Rack", category: "Furniture", price: 1599, stock: 25, description: "Metal rack, 4 shelves.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Laptop Table", category: "Furniture", price: 899, stock: 40, description: "Foldable bed table.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Wall Mirror", category: "Furniture", price: 1200, stock: 20, description: "Decorative round mirror.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Coffee Table", category: "Furniture", price: 2499, stock: 12, description: "Modern glass top table.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Wardrobe", category: "Furniture", price: 8999, stock: 8, description: "3-door wooden wardrobe.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dining Chair Set", category: "Furniture", price: 4999, stock: 15, description: "Set of 4 wooden chairs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "TV Stand", category: "Furniture", price: 3999, stock: 10, description: "Wooden stand for TVs up to 55 inches.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Recliner Sofa", category: "Furniture", price: 14999, stock: 5, description: "Leather recliner for living room.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bookshelf with Drawers", category: "Furniture", price: 5999, stock: 7, description: "5-tier wooden bookshelf with storage.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Futon Sofa Bed", category: "Furniture", price: 7999, stock: 6, description: "Convertible sofa bed.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Corner Shelf", category: "Furniture", price: 1999, stock: 10, description: "Space-saving corner shelf.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "TV Wall Mount", category: "Furniture", price: 1499, stock: 20, description: "Adjustable wall mount for TVs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Storage Ottoman", category: "Furniture", price: 2999, stock: 15, description: "Multi-purpose storage ottoman.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
    { name: "Bookshelf with Drawers", category: "Furniture", price: 5999, stock: 7, description: "5-tier wooden bookshelf with storage.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
    { name: "Futon Sofa Bed", category: "Furniture", price: 7999, stock: 6, description: "Convertible sofa bed.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
    { name: "Corner Shelf", category: "Furniture", price: 1999, stock: 10, description: "Space-saving corner shelf.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
    { name: "TV Wall Mount", category: "Furniture", price: 1499, stock: 20, description: "Adjustable wall mount for TVs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
    { name: "Storage Ottoman", category: "Furniture", price: 2999, stock: 15, description: "Multi-purpose storage ottoman.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bookshelf with Drawers", category: "Furniture", price: 5999, stock: 7, description: "5-tier wooden bookshelf with storage.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Futon Sofa Bed", category: "Furniture", price: 7999, stock: 6, description: "Convertible sofa bed.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Corner Shelf", category: "Furniture", price: 1999, stock: 10, description: "Space-saving corner shelf.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "TV Wall Mount", category: "Furniture", price: 1499, stock: 20, description: "Adjustable wall mount for TVs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Storage Ottoman", category: "Furniture", price: 2999, stock: 15, description: "Multi-purpose storage ottoman.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Folding Chair", category: "Furniture", price: 999, stock: 50, description: "Portable metal chair.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bedside Lamp", category: "Furniture", price: 799, stock: 35, description: "Warm light, modern design.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

  // Pet Supplies
  { name: "Dog Food Bowl", category: "Pet Supplies", price: 299, stock: 50, description: "Stainless steel, non-slip.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cat Food Bowl", category: "Pet Supplies", price: 249, stock: 45, description: "Ceramic bowl with paw print.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Carrier", category: "Pet Supplies", price: 1999, stock: 20, description: "Portable travel carrier.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dog Chew Toy", category: "Pet Supplies", price: 399, stock: 60, description: "Durable rubber toy.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cat Scratching Mat", category: "Pet Supplies", price: 499, stock: 30, description: "Corrugated cardboard mat.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Grooming Brush", category: "Pet Supplies", price: 299, stock: 40, description: "For dogs and cats.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bird Seed Mix", category: "Pet Supplies", price: 399, stock: 25, description: "For small birds.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Aquarium Gravel", category: "Pet Supplies", price: 599, stock: 15, description: "Decorative gravel for fish tanks.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Water Fountain", category: "Pet Supplies", price: 1499, stock: 10, description: "Automatic water dispenser.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet First Aid Kit", category: "Pet Supplies", price: 799, stock: 20, description: "Emergency supplies for pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dog Bed", category: "Pet Supplies", price: 1299, stock: 15, description: "Soft and cozy bed for dogs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cat Tree", category: "Pet Supplies", price: 2499, stock: 10, description: "Multi-level cat climbing tree.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Nail Clippers", category: "Pet Supplies", price: 399, stock: 30, description: "Stainless steel clippers.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Travel Bag", category: "Pet Supplies", price: 1999, stock: 20, description: "For carrying pets during travel.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Water Bottle", category: "Pet Supplies", price: 499, stock: 50, description: "Portable water bottle for pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Food Storage Container", category: "Pet Supplies", price: 899, stock: 25, description: "Airtight container for pet food.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Training Pads", category: "Pet Supplies", price: 699, stock: 40, description: "Absorbent pads for pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Hair Remover Roller", category: "Pet Supplies", price: 299, stock: 60, description: "Sticky roller for pet hair.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Cooling Mat", category: "Pet Supplies", price: 1299, stock: 20, description: "Gel mat to keep pets cool.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Travel Carrier", category: "Pet Supplies", price: 2499, stock: 15, description: "Comfortable carrier for pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Feeding Station", category: "Pet Supplies", price: 1999, stock: 10, description: "Elevated feeding station for pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Grooming Kit", category: "Pet Supplies", price: 1499, stock: 30, description: "Complete grooming kit for pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Travel Water Bottle", category: "Pet Supplies", price: 599, stock: 50, description: "Portable water bottle for pets on the go.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Cooling Vest", category: "Pet Supplies", price: 1799, stock: 20, description: "Cooling vest for pets during hot weather.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Travel Backpack", category: "Pet Supplies", price: 2999, stock: 15, description: "Backpack carrier for small pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Dental Chews", category: "Pet Supplies", price: 499, stock: 40, description: "Dental chews for dogs and cats.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Travel Stroller", category: "Pet Supplies", price: 3999, stock: 10, description: "Stroller for small pets.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pedigree Dog Food (3kg)", category: "Pet Supplies", price: 699, stock: 40, description: "Chicken and vegetables.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Whiskas Cat Food (1kg)", category: "Pet Supplies", price: 450, stock: 35, description: "Tuna flavor.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dog Leash", category: "Pet Supplies", price: 299, stock: 50, description: "Nylon, 5 feet.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cat Litter (5kg)", category: "Pet Supplies", price: 599, stock: 30, description: "Odor control sand.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Shampoo", category: "Pet Supplies", price: 350, stock: 45, description: "Anti-tick and flea.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Chew Toy", category: "Pet Supplies", price: 199, stock: 60, description: "Rubber bone for dogs.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Fish Food", category: "Pet Supplies", price: 150, stock: 80, description: "Flakes for aquarium fish.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Pet Bed", category: "Pet Supplies", price: 999, stock: 20, description: "Soft cushion, medium size.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Bird Cage", category: "Pet Supplies", price: 1200, stock: 10, description: "Metal cage with perch.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Dog Collar", category: "Pet Supplies", price: 250, stock: 55, description: "Adjustable with bell.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },
  { name: "Cat Scratching Post", category: "Pet Supplies", price: 799, stock: 25, description: "Sisal rope, vertical post.", imageUrl: "https://m.media-amazon.com/images/I/61Kf6WbQWyL._SL1500_.jpg" },

];

const seedData = async () => {
  try {
    await connectDB();
    await Product.deleteMany(); // Clear existing data
    console.log("Deleted old products...");
    
    await Product.insertMany(products);
    console.log("Added new products!");
    
    process.exit();
  } catch (error) {
    console.error("Error seeding data:", error);
    process.exit(1);
  }
};

seedData();